name: Validate Content Batches

on:
  pull_request:
    paths:
      - 'data/batches/**/*.json'
  workflow_dispatch: {}   # allow manual run from Actions tab

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate Glossary Batches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # no caching so we don't need a lock file

      - name: Install runtime deps
        run: |
          npm init -y
          npm install --no-audit --no-fund typescript ts-node zod ajv ajv-formats glob

      - name: Validate JSON batches (ESM + ts-node)
        run: |
          # minimal tsconfig so ts-node knows to use ESM
          printf '{ "compilerOptions": { "module": "esnext", "moduleResolution": "bundler", "target": "ES2020" } }\n' > tsconfig.json
          node --loader ts-node/esm scripts/validate-batch.ts "data/batches/**/*.json"

      # Optional: if this still 403s for you, just delete this whole step.
      - name: Comment summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const body = "✅ Validation ran. See logs above for pass/warn/error details.";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });


