name: Validate Content Batches

on:
  pull_request:
    paths:
      - 'data/batches/**/*.json'
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate Glossary Batches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # no caching; we install tiny runtime deps each run

      - name: Install runtime deps
        run: |
          npm init -y
          npm install --no-audit --no-fund typescript ts-node zod ajv ajv-formats glob

      # Force ts-node to transpile as CommonJS (avoids ESM loader issues)
      - name: Create minimal tsconfig
        run: |
          cat > tsconfig.json << 'JSON'
          {
            "compilerOptions": {
              "target": "ES2020",
              "module": "commonjs",
              "moduleResolution": "node",
              "esModuleInterop": true,
              "resolveJsonModule": true,
              "skipLibCheck": true
            }
          }
          JSON

      - name: Validate JSON batches
        run: npx ts-node --transpile-only --compiler-options '{"module":"commonjs","moduleResolution":"node","esModuleInterop":true,"target":"ES2020","resolveJsonModule":true,"skipLibCheck":true}' scripts/validate-batch.ts "data/batches/**/*.json"

      # If this step 403s for you, delete it; it's optional.
      - name: Comment summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const body = "✅ Validation ran. See logs above for pass/warn/error details.";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
