name: Validate Content Batches

on:
  pull_request:
    paths:
      - 'data/batches/**/*.json'
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate Glossary Batches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install runtime deps
        run: |
          npm init -y
          npm install --no-audit --no-fund typescript ts-node zod ajv ajv-formats glob

      - name: Create minimal tsconfig
        run: |
          cat > tsconfig.json << 'JSON'
          {
            "compilerOptions": {
              "target": "ES2020",
              "module": "commonjs",
              "moduleResolution": "node",
              "esModuleInterop": true,
              "resolveJsonModule": true,
              "skipLibCheck": true
            }
          }
          JSON

      # Find only the batch files changed in this PR
      - name: Get changed batch files
        id: changed
        uses: tj-actions/changed-files@v41
        with:
          files: |
            data/batches/**/*.json

      - name: Show changed files
        run: |
          echo "Changed: ${{ steps.changed.outputs.all_changed_files }}"

      - name: Validate each changed batch
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          for f in ${{ steps.changed.outputs.all_changed_files }}; do
            echo "Validating $f"
            npx ts-node --transpile-only --compiler-options '{"module":"commonjs","moduleResolution":"node","esModuleInterop":true,"target":"ES2020","resolveJsonModule":true,"skipLibCheck":true}' scripts/validate-batch.ts "$f"
          done

      - name: No batch files changed
        if: steps.changed.outputs.any_changed != 'true'
        run: echo "No data/batches/*.json files changed in this PR."

      # Optional PR comment — delete this step if it 403s again
      - name: Comment summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const body = "✅ Validation ran. See logs above for pass/warn/error details.";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
